Fixes some formal wording
pretalx/pretalx-public-voting pull request #19
Opened 2021-02-13 09:50 UTC by astroidex

2021-02-13 20:27 UTC, vmx approved these changes

2021-02-15 09:13 UTC, rixx requested changes
Es wäre vermutlich gut, dieselben Änderungen auch beim de_DE-Übersetzungsfile nachzuziehen, damit die beiden Versionen nicht auseinander laufen.

2021-02-15 09:13 UTC, rixx commented on pretalx_public_voting/locale/de_Formal/LC_MESSAGES/django.po
> +"Vielen Dank für ihre Anmeldung zur öffentlichen Abstimmung. Sie haben soeben "
```suggestion
"Vielen Dank für Ihre Anmeldung zur öffentlichen Abstimmung. Sie haben soeben "
```

2021-02-15 09:35 UTC, vmx commented
Falls @astroidex nicht schneller ist, ziehe ich `de_DE` heute Nacht nach.

2021-02-15 23:26 UTC, vmx commented
As I couldn't push directly, I've created #22, which contains also the changes from this PR.

2021-02-16 18:03 UTC, closed without merging