Save score only if it has changed
pretalx/pretalx-public-voting pull request #8
Opened 2020-09-27 18:57 UTC by vmx

I'm not sure if that's the right approach.

An alternative version I had was:

```diff
+    def save(self, *args, **kwargs):
+        # Update the timestamp only if the score has actually changed
+        if self.existing_score != self.score:
+            self.timestamp = timezone.now()
+        super(PublicVote, self).save(*args, **kwargs)
```

2020-09-27 20:13 UTC, rixx requested changes
I think a better place for this would be in the form. `form.changed_data` holds a list of things that have actually changed, and we could test for those. Doing this on the model sounds very likely to cause hard-to-trace trouble down the line – what if I want to update something besides the vote, e.g. change the email hash from the shell? I wouldn't have any indicator that my commands don't do what I think they do.

2020-09-27 20:14 UTC, rixx commented
`auto_now_add=True` makes absolutely sure that you can't override the timestamp later on (unless you bypass the save method entirely), so that wouldn't be an option.

2020-09-27 20:50 UTC, vmx commented
> I think a better place for this would be in the form. `form.changed_data` holds a list of things that have actually changed, and we could test for those.

Thanks, I'll try to put it there.

> `auto_now_add=True` makes absolutely sure that you can't override the timestamp later on (unless you bypass the save method entirely), so that wouldn't be an option.

The above alternative worked for me, I tried it locally. Though I'll try it the recommended way as mentioned above.

2020-10-04 22:48 UTC, vmx commented
I've moved it from the model into the form. Sadly `form.hash_changed()` didn't work as expected, hence I've added a manual comparison.

2020-12-20 08:57 UTC, rixx approved these changes
:+1:

2020-12-20 08:57 UTC, merged